language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
before_install:
  - curl -s -o $HOME/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-old.phar
  - chmod +x $HOME/.phpenv/versions/5.5/bin/phpunit
script: 
  - phpunit